Feat/migrate driving school
SOZ-Faut-etre-Sub/SOZ-FiveM-Server pull request #35
Opened 2022-12-30 14:42 UTC by lanahrone

Bonjour la team,

Je n'avais pas eu l'occasion de tester le `soz-core` avant mon départ cet été. J'ai voulu tester la chose en faisant le portage de la resource `soz-driving-school` (originellement écrite en `lua`) vers `soz-core`.

Je mets quelques commentaires dans cette PR pour valider mes choix d’implémentation.

Fonctionnellement, la feature est identique à l’originale. À une exception près : j’ai déplacé le checkpoint de la fourrière, de l’ancien emplacement de la fourrière vers l’emplacement actuel.

Je me suis noté quelques améliorations possibles, que je soumettrais ultérieurement (dans un issue [improvement], coucou @NariieL)

2022-12-30 14:44 UTC, lanahrone commented on modules.cfg
> +stop soz-driving-school
Pour le moment je n’ai pas supprimé la feature originale (`lua`)`.

Elle est simplement arrêtée manuellement dans le `modules.cfg`.

2022-12-30 14:44 UTC, lanahrone commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +    @Tick(TickInterval.EVERY_FRAME)
Dans la ressource `lua`, je spawnais des threads à la volée (`CreateThread()`) pour les boucles qui permettent de détecter le passage des checkpoints et la gestion des pénalités. Le thread se terminait une fois la boucle `while` terminée.

Ici, j’ai utilisé le décorateur `@Tick` avec un early return, basé sur un flag déclaré au niveau du Provider. Mais ça fait que la logique est quand même exécutée tout le temps même si aucun examen de permis n’est en cours.

Est-ce la bonne approche ? Ou bien y a-t-il une soz-core way ?

2022-12-31 00:24 UTC, NariieL commented
Your improvement cannot be taken in consideration at the moment.

🚂 You must first open an improvement proposal using the "Improvement" template available in the Issues.
![image](https://user-images.githubusercontent.com/104008465/210119571-7b839f76-ae62-4dd0-9421-d85435cf8969.png)
<3

2023-01-01 23:06 UTC, joelwurtz requested changes
Trop bien la PR, y a quelques ajustements à faire mais au final c'est top merci

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +    @Tick(TickInterval.EVERY_FRAME)
C'est plus ou moins la facon de faire, ca consomme pas vraiment un tick vide, donc c'est mieux je trouve, sinon l'autre solution ca consiste a créer un tick et l'assigné a une variable puis le clear quand c'est ok (on a du le faire a un autre endroit)

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/server/driving-school/ds.provider.ts
> +    private QBCore: QBCore;
Il y a un service `PlayerService` qui permet de s'abstraire de QBCore et qu'il vaut mieux utiliser pour ce cas la, tout les librairies externe au core doivent être abstraites derrière des services pour pouvoir refactor plus facilement quand on voudra les dégager

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/shared/rpc.ts
> +    DRIVING_SCHOOL_SPAWN_VEHICLE = 'soz-core:server:driving-school:soawn-vehicle',
```suggestion
    DRIVING_SCHOOL_SPAWN_VEHICLE = 'soz-core:server:driving-school:spawn-vehicle',
```

2023-01-01 23:06 UTC, joelwurtz commented on modules.cfg
> +stop soz-driving-school
Go supprimer le code, aucun problème il sera dans l'historique git si besoin

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +    private vehicleEntity: number;
un état dans le provider me dérange pas, mais j'aime bien regrouper sous un seul objet, (sauf si vraiment trop différent et rien avoir), ca permet de plus facilement comprendre / clean (en mettant a null l'objet y a plus rien), après c'est du pinaillage pour le coup

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +        this.license = DrivingSchoolConfig.licenses[licenseType];
peut être pas besoin de le faire de suite cette assignement ? mais plutot au moment du setup ? car tu envoies le type dans la paiement et tu le recois au moment du setup, ca évitera de stock un état (le moins d'état possible dans les provider c'est mieux, plus de stateless = moins d'erreurs)

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +    private vehicleEntity: number;
on pourrais par exemple faire un objet du style : 

```ts
type CurrentExam = {
    spawnPoint: Vector3;
    license: DrivingSchoolLicense;
    isPenaltyLoopRunning: bool;
    checkpoints: Checkpoint[];
    currentCheckpoint: Checkpoint;
    checkpointEntity: number;
    checkpointBlip: number;
    ...
}

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +        if (GetEntityType(veh) == EntityType.Vehicle && IsEntityDead(veh)) {
verifié si on est en exam non ? sinon on push qqchose, et c'est jamais reset cette valeur ?

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +        if (!this.isExamRunning) return;
j'ai pas mis de règle eslint, mais je voudrais éviter les if sans accolades (je rajouterais la règle soon)

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +        if (!this.isExamRunning) return;
je met pas de commentaire pour les autres mais c'est pareil

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/server/driving-school/ds.provider.ts
> +        if (!qbPlayer.Functions.RemoveMoney('money', lData.price)) {
Il y a un service spécial pour supprimer l'argent `PlayerMoneyService`

2023-01-01 23:06 UTC, joelwurtz commented on resources/[soz]/soz-core/src/shared/driving-school.ts
> +}
au final c'est exactement le même énum non ? pourquoi en faire 2 du coup ?

2023-01-03 21:14 UTC, lanahrone commented on modules.cfg
> +stop soz-driving-school
🗑️

2023-01-03 21:15 UTC, lanahrone commented on resources/[soz]/soz-core/src/server/driving-school/ds.provider.ts
> +    private QBCore: QBCore;
👌

2023-01-03 21:16 UTC, lanahrone commented on resources/[soz]/soz-core/src/shared/rpc.ts
> +    DRIVING_SCHOOL_SPAWN_VEHICLE = 'soz-core:server:driving-school:soawn-vehicle',
👌

2023-01-03 21:16 UTC, lanahrone commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +    private vehicleEntity: number;
👌

2023-01-03 21:16 UTC, lanahrone commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +        this.license = DrivingSchoolConfig.licenses[licenseType];
👌

2023-01-03 21:17 UTC, lanahrone commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +        if (GetEntityType(veh) == EntityType.Vehicle && IsEntityDead(veh)) {
👌

2023-01-03 21:17 UTC, lanahrone commented on resources/[soz]/soz-core/src/client/driving-school/exam.provider.ts
> +        if (!this.isExamRunning) return;
{👌}

2023-01-03 21:17 UTC, lanahrone commented on resources/[soz]/soz-core/src/server/driving-school/ds.provider.ts
> +        if (!qbPlayer.Functions.RemoveMoney('money', lData.price)) {
👌

2023-01-03 21:21 UTC, lanahrone commented on resources/[soz]/soz-core/src/shared/driving-school.ts
> +}
J'ai fait un autre enum (`DrivingSchoolLicenseType`) pour exclure de l'enum `PlayerLicenceType`

1. le `Boat` qui n'est pas géré par le permis actuellement
2.  et les permis qui ne concernent pas la driving school (`Weapon`, `Fishing`, `Hunting`, `Rescuer`)

2023-01-25 01:00 UTC, NariieL approved these changes

2023-03-25 23:26 UTC, joelwurtz commented
Pour info ca a été mergé il y a pas mal de temps chez nous avec qques ajustements et c'est maintenant bien dispo dans l'opensource, merci beaucoup @lanahrone pour tout le taff ❤️

2023-03-25 23:26 UTC, closed without merging